sudo: false
dist: trusty
language: java
jdk:
  - openjdk10
  - oraclejdk10
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
  - sudo riak-admin bucket-type create maps '{"props":{"datatype":"map"}}'
  - sudo riak-admin bucket-type activate maps
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

services:
  - riak

env:
  global:
    # CI_DEPLOY_USERNAME
    - secure: "S8HDSF/GUdzEt9ZVxr0zVYJSNt2uMXbE3xV8vCV8j40ri9/0z0ZJfvcZx7p6k7sscxhpRsX9KPzYvQwM9ex2O/Aw190XATDiXHbJ0jzCii0agzTSlolJ/HiGCkYzSt7rPbjzB2NKmww2qMeMvzyEoWRFV9P5171Jsm99w+qmVhpwWBogPr9FD5ayRZF78BDoU96ChbLbJxOzjg1N4IaJ6KmAbGxsQ9MLyhV+iJjRIWe9DgR8dd6ja+J4RHF+HfqYg8NJMfg7JGpTO1ULbZHoqaO5e++FkIrn/Srp/qRwfEZxWs4TxTVTMxfKQ6ss8mduOVp1nahu6OC+47pJG3MWZsdU1CDCdjbQ/CrLcVduQtS2+TZoiwdwgyYJFiSim1HWivrNGuhk4ySvonmXVZzuWXMUqAHmbq2nq4/a0HrwfF+mth5B/wgOIuYMwtwP7ibUsunc9+Rx/c+gL3X/Fr49oHvIOySkbQ6FKK23H0MF+lNEUfuqpRREOkbIyhO0sEItCIsoaeDdOw9JqicTiYodE+OkLT3c2oYN+PNtUVV8ZSxdAI5bolArwoVPMxNhSBLPqJIAHfjmAAzGbmttNGrbuARsG3xbFaQcDMDdAfxKsQLMiY2EHajMdQ6ShswMbgGWvIbsksPzYIUJw4FBWuQZcXWt/MIF86ACthPBpBxEiJc="
    # CI_DEPLOY_PASSWORD
    - secure: "WcOQLsXDzayW9bbU3mlte9vD7+gd5UmSELR8Sus+HUAdl7DphhQHS0obWNPcJJNcRCDvjoDRUFVaP+KVvAAPwIrBu4HMjhIuAJkiLu3QF382rHTSwKvZvzUA99XJPautoqmdzZofjsdMwOoQZZ/Q32kjc3qqR3MYzs9PtzWt0/oM6YNW590r+cks9MXIZ1K5UPaEIRGO6Q+IMDRzgsq5UvNtLWFAUqlU+xY5xCgubOnkGIUZfMrm1M+Jl4FJg7rT2DOuBVvMjPPlzjjAQXH3HZG/i9ET+2A/zDtxepl2QqJhc/ZhBLLywSdAhQhYIhaa0zpscv7B5e/iqbjR+1TVUimxqWjvasUVqi969iWVyTnw30LeJwuOH/DmJQ/DPguENTWMFBrl4YNSaty4L3heLsF87kJ+4mHOmuAbGEyyCSwLmAFBWRsaLH0gb5f/ng7TpElZ9FrOn+njT1Sg4t5+J7ftTPp9CujET7F6UzfD0aJU10P3qsuU1E7r9YJoaAGWdbJ4N4fKHRkuwd3EJyc0KCKaVHVHZ890tyvzrveDXHon0Mh7/Yv/lBWJ0hdvFtHTOmF1zOUjkKPdJFGTB8pKSthY9+Qlruqym9CDMc0icFB4ciwMJQaP4d4QLrHWBiRlGA2qG4mJKnAcJMyYZN2VF6V8YOiCMk9hJ06d03Aq0q8="
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"
