// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package com.smoketurner.notification.application.protos;

public final class NotificationProtos {
  private NotificationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotificationPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:notification.NotificationPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string category = 2;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>optional string category = 2;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional int64 created_at = 4;</code>
     */
    long getCreatedAt();

    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */
    int getPropertyCount();
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */
    boolean containsProperty(
        java.lang.String key);
    /**
     * Use {@link #getPropertyMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getProperty();
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getPropertyMap();
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    java.lang.String getPropertyOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    java.lang.String getPropertyOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code notification.NotificationPB}
   */
  public  static final class NotificationPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:notification.NotificationPB)
      NotificationPBOrBuilder {
    // Use NotificationPB.newBuilder() to construct.
    private NotificationPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotificationPB() {
      id_ = 0L;
      category_ = "";
      message_ = "";
      createdAt_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NotificationPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 32: {

              createdAt_ = input.readInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                property_ = com.google.protobuf.MapField.newMapField(
                    PropertyDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              property = input.readMessage(
                  PropertyDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              property_.getMutableMap().put(property.getKey(), property.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetProperty();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.class, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 2;
    private volatile java.lang.Object category_;
    /**
     * <code>optional string category = 2;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>optional string category = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_AT_FIELD_NUMBER = 4;
    private long createdAt_;
    /**
     * <code>optional int64 created_at = 4;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int PROPERTY_FIELD_NUMBER = 5;
    private static final class PropertyDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_PropertyEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> property_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperty() {
      if (property_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertyDefaultEntryHolder.defaultEntry);
      }
      return property_;
    }

    public int getPropertyCount() {
      return internalGetProperty().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    public boolean containsProperty(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProperty().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertyMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperty() {
      return getPropertyMap();
    }
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getPropertyMap() {
      return internalGetProperty().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    public java.lang.String getPropertyOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperty().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; property = 5;</code>
     */

    public java.lang.String getPropertyOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperty().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, category_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(4, createdAt_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperty().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        property = PropertyDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(5, property);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, category_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createdAt_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperty().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        property = PropertyDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, property);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB)) {
        return super.equals(obj);
      }
      com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB other = (com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && (getCreatedAt()
          == other.getCreatedAt());
      result = result && internalGetProperty().equals(
          other.internalGetProperty());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedAt());
      if (!internalGetProperty().getMap().isEmpty()) {
        hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProperty().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code notification.NotificationPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:notification.NotificationPB)
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetProperty();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableProperty();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.class, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder.class);
      }

      // Construct using com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        category_ = "";

        message_ = "";

        createdAt_ = 0L;

        internalGetMutableProperty().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationPB_descriptor;
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getDefaultInstanceForType() {
        return com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.getDefaultInstance();
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB build() {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB buildPartial() {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB result = new com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.category_ = category_;
        result.message_ = message_;
        result.createdAt_ = createdAt_;
        result.property_ = internalGetProperty();
        result.property_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB) {
          return mergeFrom((com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB other) {
        if (other == com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getCreatedAt() != 0L) {
          setCreatedAt(other.getCreatedAt());
        }
        internalGetMutableProperty().mergeFrom(
            other.internalGetProperty());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>optional string category = 2;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string category = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 2;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 2;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 2;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private long createdAt_ ;
      /**
       * <code>optional int64 created_at = 4;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>optional int64 created_at = 4;</code>
       */
      public Builder setCreatedAt(long value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 created_at = 4;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> property_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProperty() {
        if (property_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropertyDefaultEntryHolder.defaultEntry);
        }
        return property_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProperty() {
        onChanged();;
        if (property_ == null) {
          property_ = com.google.protobuf.MapField.newMapField(
              PropertyDefaultEntryHolder.defaultEntry);
        }
        if (!property_.isMutable()) {
          property_ = property_.copy();
        }
        return property_;
      }

      public int getPropertyCount() {
        return internalGetProperty().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public boolean containsProperty(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetProperty().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPropertyMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getProperty() {
        return getPropertyMap();
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getPropertyMap() {
        return internalGetProperty().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public java.lang.String getPropertyOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperty().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public java.lang.String getPropertyOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperty().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearProperty() {
        getMutableProperty().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public Builder removeProperty(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableProperty().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProperty() {
        return internalGetMutableProperty().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */
      public Builder putProperty(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableProperty().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; property = 5;</code>
       */

      public Builder putAllProperty(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableProperty().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:notification.NotificationPB)
    }

    // @@protoc_insertion_point(class_scope:notification.NotificationPB)
    private static final com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB();
    }

    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotificationPB>
        PARSER = new com.google.protobuf.AbstractParser<NotificationPB>() {
      public NotificationPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NotificationPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotificationPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotificationPB> getParserForType() {
      return PARSER;
    }

    public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NotificationListPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:notification.NotificationListPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> 
        getNotificationList();
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getNotification(int index);
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    int getNotificationCount();
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    java.util.List<? extends com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder> 
        getNotificationOrBuilderList();
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder getNotificationOrBuilder(
        int index);

    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    java.util.List<java.lang.Long> getDeletedIdList();
    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    int getDeletedIdCount();
    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    long getDeletedId(int index);
  }
  /**
   * Protobuf type {@code notification.NotificationListPB}
   */
  public  static final class NotificationListPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:notification.NotificationListPB)
      NotificationListPBOrBuilder {
    // Use NotificationListPB.newBuilder() to construct.
    private NotificationListPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotificationListPB() {
      notification_ = java.util.Collections.emptyList();
      deletedId_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NotificationListPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                notification_ = new java.util.ArrayList<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB>();
                mutable_bitField0_ |= 0x00000001;
              }
              notification_.add(
                  input.readMessage(com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.parser(), extensionRegistry));
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                deletedId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              deletedId_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                deletedId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                deletedId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          notification_ = java.util.Collections.unmodifiableList(notification_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          deletedId_ = java.util.Collections.unmodifiableList(deletedId_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationListPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationListPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.class, com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.Builder.class);
    }

    public static final int NOTIFICATION_FIELD_NUMBER = 1;
    private java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> notification_;
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    public java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> getNotificationList() {
      return notification_;
    }
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    public java.util.List<? extends com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder> 
        getNotificationOrBuilderList() {
      return notification_;
    }
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    public int getNotificationCount() {
      return notification_.size();
    }
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getNotification(int index) {
      return notification_.get(index);
    }
    /**
     * <code>repeated .notification.NotificationPB notification = 1;</code>
     */
    public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder getNotificationOrBuilder(
        int index) {
      return notification_.get(index);
    }

    public static final int DELETED_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> deletedId_;
    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getDeletedIdList() {
      return deletedId_;
    }
    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    public int getDeletedIdCount() {
      return deletedId_.size();
    }
    /**
     * <code>repeated int64 deleted_id = 2;</code>
     */
    public long getDeletedId(int index) {
      return deletedId_.get(index);
    }
    private int deletedIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < notification_.size(); i++) {
        output.writeMessage(1, notification_.get(i));
      }
      if (getDeletedIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(deletedIdMemoizedSerializedSize);
      }
      for (int i = 0; i < deletedId_.size(); i++) {
        output.writeInt64NoTag(deletedId_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < notification_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, notification_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < deletedId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(deletedId_.get(i));
        }
        size += dataSize;
        if (!getDeletedIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        deletedIdMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB)) {
        return super.equals(obj);
      }
      com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB other = (com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB) obj;

      boolean result = true;
      result = result && getNotificationList()
          .equals(other.getNotificationList());
      result = result && getDeletedIdList()
          .equals(other.getDeletedIdList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getNotificationCount() > 0) {
        hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getNotificationList().hashCode();
      }
      if (getDeletedIdCount() > 0) {
        hash = (37 * hash) + DELETED_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDeletedIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code notification.NotificationListPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:notification.NotificationListPB)
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationListPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationListPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.class, com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.Builder.class);
      }

      // Construct using com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNotificationFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (notificationBuilder_ == null) {
          notification_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          notificationBuilder_.clear();
        }
        deletedId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smoketurner.notification.application.protos.NotificationProtos.internal_static_notification_NotificationListPB_descriptor;
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB getDefaultInstanceForType() {
        return com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.getDefaultInstance();
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB build() {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB buildPartial() {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB result = new com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB(this);
        int from_bitField0_ = bitField0_;
        if (notificationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            notification_ = java.util.Collections.unmodifiableList(notification_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.notification_ = notification_;
        } else {
          result.notification_ = notificationBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          deletedId_ = java.util.Collections.unmodifiableList(deletedId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.deletedId_ = deletedId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB) {
          return mergeFrom((com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB other) {
        if (other == com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB.getDefaultInstance()) return this;
        if (notificationBuilder_ == null) {
          if (!other.notification_.isEmpty()) {
            if (notification_.isEmpty()) {
              notification_ = other.notification_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNotificationIsMutable();
              notification_.addAll(other.notification_);
            }
            onChanged();
          }
        } else {
          if (!other.notification_.isEmpty()) {
            if (notificationBuilder_.isEmpty()) {
              notificationBuilder_.dispose();
              notificationBuilder_ = null;
              notification_ = other.notification_;
              bitField0_ = (bitField0_ & ~0x00000001);
              notificationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNotificationFieldBuilder() : null;
            } else {
              notificationBuilder_.addAllMessages(other.notification_);
            }
          }
        }
        if (!other.deletedId_.isEmpty()) {
          if (deletedId_.isEmpty()) {
            deletedId_ = other.deletedId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDeletedIdIsMutable();
            deletedId_.addAll(other.deletedId_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> notification_ =
        java.util.Collections.emptyList();
      private void ensureNotificationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          notification_ = new java.util.ArrayList<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB>(notification_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder> notificationBuilder_;

      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> getNotificationList() {
        if (notificationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notification_);
        } else {
          return notificationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public int getNotificationCount() {
        if (notificationBuilder_ == null) {
          return notification_.size();
        } else {
          return notificationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB getNotification(int index) {
        if (notificationBuilder_ == null) {
          return notification_.get(index);
        } else {
          return notificationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder setNotification(
          int index, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationIsMutable();
          notification_.set(index, value);
          onChanged();
        } else {
          notificationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder setNotification(
          int index, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          ensureNotificationIsMutable();
          notification_.set(index, builderForValue.build());
          onChanged();
        } else {
          notificationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder addNotification(com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationIsMutable();
          notification_.add(value);
          onChanged();
        } else {
          notificationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder addNotification(
          int index, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationIsMutable();
          notification_.add(index, value);
          onChanged();
        } else {
          notificationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder addNotification(
          com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          ensureNotificationIsMutable();
          notification_.add(builderForValue.build());
          onChanged();
        } else {
          notificationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder addNotification(
          int index, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          ensureNotificationIsMutable();
          notification_.add(index, builderForValue.build());
          onChanged();
        } else {
          notificationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder addAllNotification(
          java.lang.Iterable<? extends com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB> values) {
        if (notificationBuilder_ == null) {
          ensureNotificationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, notification_);
          onChanged();
        } else {
          notificationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          notification_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          notificationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public Builder removeNotification(int index) {
        if (notificationBuilder_ == null) {
          ensureNotificationIsMutable();
          notification_.remove(index);
          onChanged();
        } else {
          notificationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder getNotificationBuilder(
          int index) {
        return getNotificationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder getNotificationOrBuilder(
          int index) {
        if (notificationBuilder_ == null) {
          return notification_.get(index);  } else {
          return notificationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public java.util.List<? extends com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder> 
           getNotificationOrBuilderList() {
        if (notificationBuilder_ != null) {
          return notificationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notification_);
        }
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder addNotificationBuilder() {
        return getNotificationFieldBuilder().addBuilder(
            com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.getDefaultInstance());
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder addNotificationBuilder(
          int index) {
        return getNotificationFieldBuilder().addBuilder(
            index, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.getDefaultInstance());
      }
      /**
       * <code>repeated .notification.NotificationPB notification = 1;</code>
       */
      public java.util.List<com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder> 
           getNotificationBuilderList() {
        return getNotificationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          notificationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPB.Builder, com.smoketurner.notification.application.protos.NotificationProtos.NotificationPBOrBuilder>(
                  notification_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          notification_ = null;
        }
        return notificationBuilder_;
      }

      private java.util.List<java.lang.Long> deletedId_ = java.util.Collections.emptyList();
      private void ensureDeletedIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          deletedId_ = new java.util.ArrayList<java.lang.Long>(deletedId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getDeletedIdList() {
        return java.util.Collections.unmodifiableList(deletedId_);
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public int getDeletedIdCount() {
        return deletedId_.size();
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public long getDeletedId(int index) {
        return deletedId_.get(index);
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public Builder setDeletedId(
          int index, long value) {
        ensureDeletedIdIsMutable();
        deletedId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public Builder addDeletedId(long value) {
        ensureDeletedIdIsMutable();
        deletedId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public Builder addAllDeletedId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDeletedIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deletedId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 deleted_id = 2;</code>
       */
      public Builder clearDeletedId() {
        deletedId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:notification.NotificationListPB)
    }

    // @@protoc_insertion_point(class_scope:notification.NotificationListPB)
    private static final com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB();
    }

    public static com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotificationListPB>
        PARSER = new com.google.protobuf.AbstractParser<NotificationListPB>() {
      public NotificationListPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NotificationListPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotificationListPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotificationListPB> getParserForType() {
      return PARSER;
    }

    public com.smoketurner.notification.application.protos.NotificationProtos.NotificationListPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationPB_PropertyEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationPB_PropertyEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationListPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationListPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022notification.proto\022\014notification\"\302\001\n\016N" +
      "otificationPB\022\n\n\002id\030\001 \001(\003\022\020\n\010category\030\002 " +
      "\001(\t\022\017\n\007message\030\003 \001(\t\022\022\n\ncreated_at\030\004 \001(\003" +
      "\022<\n\010property\030\005 \003(\0132*.notification.Notifi" +
      "cationPB.PropertyEntry\032/\n\rPropertyEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\\\n\022Notif" +
      "icationListPB\0222\n\014notification\030\001 \003(\0132\034.no" +
      "tification.NotificationPB\022\022\n\ndeleted_id\030" +
      "\002 \003(\003BG\n/com.smoketurner.notification.ap" +
      "plication.protosB\022NotificationProtosH\001b\006",
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_notification_NotificationPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_notification_NotificationPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationPB_descriptor,
        new java.lang.String[] { "Id", "Category", "Message", "CreatedAt", "Property", });
    internal_static_notification_NotificationPB_PropertyEntry_descriptor =
      internal_static_notification_NotificationPB_descriptor.getNestedTypes().get(0);
    internal_static_notification_NotificationPB_PropertyEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationPB_PropertyEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_notification_NotificationListPB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_notification_NotificationListPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationListPB_descriptor,
        new java.lang.String[] { "Notification", "DeletedId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
